experiment:
  name: walker_ppo_visual_continuous
  device: cuda
  seed: 0

environment:
  env_id: Walker2d-v5
  obs_h: 84
  obs_w: 84
  frame_stack: 4
  grayscale: true
  action_repeat: 1
  time_limit: 1000

architecture:
  hidden_dim: 256

ppo:
  actor_lr: 3e-4
  gamma: 0.99
  lambd: 0.95
  k_epochs: 10
  eps_clip: 0.2
  entropy_coef: 0.02
  value_coef: 0.5
  max_grad_norm: 0.5
  minibatch_size: 256

train:
  total_steps: 3000000
  rollout_size: 2048
  checkpoint_freq: 50000
  video_freq: 50000
  num_videos: 4
  eval_freq: 10000
  eval_episodes: 5

logging:
  save_freq: 50000
  log_dir: runs/ppo
